version: '3'

services:

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306

  py3: &py3
    build: .
    volumes:
      - ./:/usr/src/

  test:
    <<: *py3
    command: pipenv run python -m pytest --cov=/usr/src/
    environment:
      MYSQL_HOST: mysql
    depends_on:
      - mysql

  coverage:
    <<: *py3
    command: codecov
