db:
  name: qcdb_dev
  params:
    host: 
    port:
    user: 
    password: 
files:
  - name: fastqc
    directory: /Users/jwalla12/Repositories/qcdb/tests/data
  - name: qckitfastq
    directory: /Users/jwalla12/Repositories/qcdb/tests/data
  - name: picardtools
    directory: /Users/jwalla12/Repositories/qcdb/tests/data
