db:
  name: qcdb
  params:
    host: 127.0.0.1
    port: 3306
    user: root
    password: password
files:
  - name: fastqc
    directory: D:/Desktop/qcdb/tests/data/
  - name: qckitfastq
    directory: D:/Desktop/qcdb/tests/data/
  - name: picardtools
    directory: D:/Desktop/qcdb/tests/data/
