db:
  name: qcdb
  params:
    host: 127.0.0.1
    port: 3306
    user: root
    password: password
files:
  - name: fastqc
    directory: /Users/aguang/CORE/qcdb/qcdb/tests/data/
  - name: qckitfastq
    directory: /Users/aguang/CORE/qcdb/qcdb/tests/data/
  - name: picardtools
    directory: /Users/aguang/CORE/qcdb/qcdb/tests/data/
