name: Test CI 

# Only trigger when push to dev is made 
on:
  push:
    branches: 
      - devel
    paths:
      - tests/data/**

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Start containers
      run: docker-compose -f "docker-compose.yml" up 
    
